name: Ensure tag targets package
description: Validates that the tag targets the given package using the format @nike-release-checker/<package>@<version>.
outputs:
  should_skip:
    description: Whether downstream steps should skip because the tag is for another package.
    value: ${{ steps.validate.outputs.should_skip }}
  reason:
    description: A short message describing why the validation requested skipping.
    value: ${{ steps.validate.outputs.reason }}
inputs:
  package:
    description: Package name expected in the tag (e.g. cli, sdk)
    required: true
  tag:
    description: Tag name to validate
    required: true
runs:
  using: composite
  steps:
    - id: validate
      name: Validate tag matches package
      shell: bash
      run: |
        set -euo pipefail

        package="${{ inputs.package }}"
        tag="${{ inputs.tag }}"

        if [[ -z "$package" ]]; then
          echo "package input is required."
          exit 1
        fi

        if [[ -z "$tag" ]]; then
          echo "Could not determine tag name. Provide it via the 'tag' input."
          exit 1
        fi

        expected_prefix="@nike-release-checker/${package}@"

        if [[ "$tag" != ${expected_prefix}* ]]; then
          echo "::warning::Tag '${tag}' does not target package '${package}'. Expected prefix '${expected_prefix}<version>'."
          echo "should_skip=true" >> "$GITHUB_OUTPUT"
          echo "reason=Tag '${tag}' does not target package '${package}'." >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "should_skip=false" >> "$GITHUB_OUTPUT"
        echo "reason=" >> "$GITHUB_OUTPUT"
        echo "Validated: tag '${tag}' targets package '${package}'."