export const availableCountries = {
  AU: { country: 'Australia', language: 'en-GB', emoji: ' 🇦🇺  ' },
  CN: { country: 'China', language: 'zh-Hans', emoji: ' 🇨🇳  ' },
  IN: { country: 'India', language: 'en-GB', emoji: ' 🇮🇳  ' },
  ID: { country: 'Indonesia', language: 'en-GB', emoji: ' 🇮🇩  ' },
  JP: { country: 'Japan', language: 'ja', emoji: ' 🇯🇵  ' },
  MY: { country: 'Malaysia', language: 'en-GB', emoji: ' 🇲🇾  ' },
  NZ: { country: 'New Zealand', language: 'en-GB', emoji: ' 🇳🇿  ' },
  PH: { country: 'Philippines', language: 'en-GB', emoji: ' 🇵🇭  ' },
  SG: { country: 'Singapore', language: 'en-GB', emoji: ' 🇸🇬  ' },
  TW: { country: 'Taiwan', language: 'zh-Hant', emoji: ' 🇹🇼  ' },
  TH: { country: 'Thailand', language: 'th', emoji: ' 🇹🇭  ' },
  VN: { country: 'Vietnam', language: 'en-GB', emoji: ' 🇻🇳  ' },
  EG: { country: 'Egypt', language: 'en-GB', emoji: ' 🇪🇬  ' },
  MA: { country: 'Morocco', language: 'en-GB', emoji: ' 🇲🇦  ' },
  ZA: { country: 'South Africa', language: 'en-GB', emoji: ' 🇿🇦  ' },
  CA: { country: 'Canada', language: 'en-GB', emoji: ' 🇨🇦  ' },
  CL: { country: 'Chile', language: 'es-419', emoji: ' 🇨🇱  ' },
  MX: { country: 'Mexico', language: 'es-419', emoji: ' 🇲🇽  ' },
  PR: { country: 'Puerto Rico', language: 'es-419', emoji: ' 🇵🇷  ' },
  US: { country: 'United States', language: 'en', emoji: ' 🇺🇸  ' },
  UY: { country: 'Uruguay', language: 'es-419', emoji: ' 🇺🇾  ' },
  SA: { country: 'Saudi Arabia', language: 'en-GB', emoji: ' 🇸🇦  ' },
  AE: { country: 'United Arab Emirates', language: 'en-GB', emoji: ' 🇦🇪  ' },
  AT: { country: 'Austria', language: 'de', emoji: ' 🇦🇹  ' },
  BE: { country: 'Belgium', language: 'de', emoji: ' 🇧🇪  ' },
  BG: { country: 'Bulgaria', language: 'en-GB', emoji: ' 🇧🇬  ' },
  HR: { country: 'Croatia', language: 'en-GB', emoji: ' 🇭🇷  ' },
  CZ: { country: 'Czechia', language: 'cs', emoji: ' 🇨🇿  ' },
  DK: { country: 'Denmark', language: 'da', emoji: ' 🇩🇰  ' },
  FI: { country: 'Finland', language: 'en-GB', emoji: ' 🇫🇮  ' },
  FR: { country: 'France', language: 'fr', emoji: ' 🇫🇷  ' },
  DE: { country: 'Germany', language: 'de', emoji: ' 🇩🇪  ' },
  GR: { country: 'Greece', language: 'el', emoji: ' 🇬🇷  ' },
  HU: { country: 'Hungary', language: 'en-GB', emoji: ' 🇭🇺  ' },
  IE: { country: 'Ireland', language: 'en-GB', emoji: ' 🇮🇪  ' },
  IL: { country: 'Israel', language: 'en-GB', emoji: ' 🇮🇱  ' },
  IT: { country: 'Italy', language: 'it', emoji: ' 🇮🇹  ' },
  LU: { country: 'Luxembourg', language: 'en-GB', emoji: ' 🇱🇺  ' },
  NL: { country: 'Netherlands', language: 'nl', emoji: ' 🇳🇱  ' },
  NO: { country: 'Norway', language: 'no', emoji: ' 🇳🇴  ' },
  PL: { country: 'Poland', language: 'pl', emoji: ' 🇵🇱  ' },
  PT: { country: 'Portugal', language: 'pt-PT', emoji: ' 🇵🇹  ' },
  RO: { country: 'Romania', language: 'en-GB', emoji: ' 🇷🇴  ' },
  RU: { country: 'Russia', language: 'ru', emoji: ' 🇷🇺  ' },
  SK: { country: 'Slovakia', language: 'en-GB', emoji: ' 🇸🇰  ' },
  SI: { country: 'Slovenia', language: 'en-GB', emoji: ' 🇸🇮  ' },
  ES: { country: 'Spain', language: 'es-ES', emoji: ' 🇪🇸  ' },
  SE: { country: 'Sweden', language: 'sv', emoji: ' 🇸🇪  ' },
  CH: { country: 'Switzerland', language: 'en-GB', emoji: ' 🇨🇭  ' },
  TR: { country: 'Turkey', language: 'tr', emoji: ' 🇹🇷  ' },
  GB: { country: 'United Kingdom', language: 'en-GB', emoji: ' 🇬🇧  ' },
}
