name: Install workspace
description: Checkout, set Node from .nvmrc, and install dependencies
runs:
  using: composite
  steps:
    - name: Use Node version from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: npm

    - name: Install dependencies
      run: npm ci
      shell: bash
